### PR TITLE
Add assertion snippets

### PR DESCRIPTION
**Pull request by sotojuan**
This adds assertion snippets. Completely open to suggestions. I personally prefer really short snippets, but for now these are just the same as the assertion but without a period.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
In VS Code we decided to use `t.notOk` as snippet name. Because of fuzzy matching, `tnk` + <kbd>Tab</kbd> works as well.

**Comment by sotojuan** [comment]
Yeah I was wondering about the `.`s. I think it'd be better if all snippets were the same across all editors, so think I am going to change to that.

**Comment by SamVerschueren** [comment]
LGTM

**Comment by sindresorhus** [comment]
The indentation is off and the JSON is invalid.

**Comment by sotojuan** [comment]
Sorry about that, I'm blind when it comes to JSON. Should be fine now (at least the JSON validator Sublime plugin says it is).

**Pull request closed without merging**
